### ISSUE TITLE
Set up Travis to run test suite and check the code formatting

### ISSUE THREAD

**Issue by aubreypc** [inTestiGator/pytest-encourage#1]
Before we get too far into the project, it would be good to perform our initial Travis setup so that we can get a sense for whether our builds are working or not. We can have Travis run the test suite, as well as run black / flake8 / pylint  in order to ensure that the code is formatted properly. The [.travis.yml file for gatorgrouper](https://github.com/GatorEducator/gatorgrouper/blob/master/.travis.yml) might be a good starting point.

**Comment by finneyj2** [comment]
Travis has been set up and pip files have been added
